# Generated by Django 4.2.4 on 2023-09-23 09:22

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='parent',
            field=djongo.models.fields.ArrayReferenceField(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
