# Generated by Django 4.2.4 on 2023-09-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_categorymodel_parent_alter_categorymodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.categorymodel'),
        ),
    ]
