# Generated by Django 4.2.4 on 2023-09-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='thumbnail',
        ),
    ]
