# Generated by Django 4.2.4 on 2023-09-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0002_productmodel_category_alter_categorymodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel'),
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
