# Generated by Django 4.2.4 on 2023-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productmodel_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumnails/'),
        ),
    ]
