# Generated by Django 4.2.4 on 2023-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_picture_productmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumnails/'),
        ),
    ]
