# Generated by Django 4.2.4 on 2023-09-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0003_alter_productmodel_category_delete_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel'),
        ),
    ]
