# Generated by Django 4.2.4 on 2023-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_picture_alter_productmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='../../uploaded_media'),
        ),
    ]
