# Generated by Django 4.2.4 on 2023-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productmodel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='../pictures/'),
        ),
    ]
