# Generated by Django 4.2.4 on 2023-09-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productmodel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumnails/'),
        ),
    ]
